"""Infographic / slide image generation with AI illustrations."""
from __future__ import annotations

import base64
import logging
from pathlib import Path
from typing import Union

from core.content_structurer import PresentationOutline

logger = logging.getLogger(__name__)


def prepare_slide_deck_content(outline: PresentationOutline) -> str:
    """Convert outline to markdown for baoyu-slide-deck."""
    lines = [f"# {outline.title}", "", f"> {outline.subtitle}", ""]
    for sec in outline.sections:
        lines.append(f"## {sec.title}")
        for b in sec.bullets:
            lines.append(f"- {b}")
        lines.append("")
    return "\n".join(lines)


SLIDE_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { width: 1280px; height: 720px; font-family: -apple-system, "PingFang SC", "Noto Sans SC", "Microsoft YaHei", sans-serif; overflow: hidden; }
.slide { width: 1280px; height: 720px; display: flex; padding: 48px 56px; position: relative; }
.slide.title-slide { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%); color: white; flex-direction: column; justify-content: center; }
.slide.title-slide .accent { width: 100px; height: 4px; background: #00d2ff; margin-bottom: 24px; border-radius: 2px; }
.slide.title-slide h1 { font-size: 44px; font-weight: 700; line-height: 1.3; margin-bottom: 16px; }
.slide.title-slide .sub { font-size: 20px; color: #9aa; }
.slide.content-slide { background: linear-gradient(180deg, #16213e 0%, #1a1a2e 100%); color: white; }
.slide.content-slide .left { flex: 1; display: flex; flex-direction: column; justify-content: center; padding-right: 40px; }
.slide.content-slide .right { width: 420px; display: flex; align-items: center; justify-content: center; }
.slide.content-slide .right img { max-width: 100%; max-height: 560px; border-radius: 12px; object-fit: cover; }
.slide.content-slide .right .placeholder { width: 100%; height: 360px; background: rgba(255,255,255,0.05); border-radius: 12px; display: flex; align-items: center; justify-content: center; color: #445; font-size: 14px; }
.slide.content-slide .num { font-size: 14px; color: #00d2ff; font-weight: 600; margin-bottom: 12px; }
.slide.content-slide h2 { font-size: 32px; font-weight: 700; margin-bottom: 10px; line-height: 1.3; }
.slide.content-slide .line { width: 60px; height: 3px; background: #00d2ff; margin-bottom: 28px; border-radius: 2px; }
.slide.content-slide .bullet { display: flex; align-items: flex-start; margin-bottom: 14px; font-size: 18px; line-height: 1.6; color: #ccc; }
.slide.content-slide .bullet .dot { color: #00d2ff; margin-right: 14px; font-size: 10px; margin-top: 7px; flex-shrink: 0; }
.slide.end-slide { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: white; flex-direction: column; justify-content: center; align-items: center; text-align: center; }
.slide.end-slide h1 { font-size: 44px; margin-bottom: 16px; }
.slide.end-slide .sub { font-size: 16px; color: #667; }
"""


def _html_page(body: str) -> str:
    return f'<!DOCTYPE html><html><head><meta charset="utf-8"><style>{SLIDE_CSS}</style></head><body>{body}</body></html>'


def _title_slide(outline: PresentationOutline) -> str:
    return _html_page(f'''<div class="slide title-slide">
  <div class="accent"></div>
  <h1>{outline.title}</h1>
  <div class="sub">{outline.subtitle}</div>
</div>''')


def _content_slide(index: int, title: str, bullets: list[str], img_b64: str = "") -> str:
    bullets_html = "\n".join(
        f'<div class="bullet"><span class="dot">●</span><span>{b}</span></div>'
        for b in bullets
    )
    if img_b64:
        img_html = f'<img src="data:image/png;base64,{img_b64}" />'
    else:
        img_html = '<div class="placeholder"></div>'

    return _html_page(f'''<div class="slide content-slide">
  <div class="left">
    <div class="num">{index:02d}</div>
    <h2>{title}</h2>
    <div class="line"></div>
    {bullets_html}
  </div>
  <div class="right">{img_html}</div>
</div>''')


def _end_slide() -> str:
    return _html_page('''<div class="slide end-slide">
  <h1>谢谢观看</h1>
  <div class="sub">Generated by Media Tool</div>
</div>''')


async def render_slides_to_images(
    outline: PresentationOutline,
    with_illustrations: bool = False,
) -> list[bytes]:
    """Render slides as PNG images. Optionally generates AI illustrations per section."""
    from playwright.async_api import async_playwright

    # Generate illustrations if requested
    section_images = []
    if with_illustrations:
        from core.image_gen import generate_illustrations_for_outline
        raw_images = generate_illustrations_for_outline(outline)
        section_images = [
            base64.b64encode(img).decode() if img else ""
            for img in raw_images
        ]

    # Pad if needed
    while len(section_images) < len(outline.sections):
        section_images.append("")

    # Build HTML pages
    pages = [_title_slide(outline)]
    for i, sec in enumerate(outline.sections):
        pages.append(_content_slide(i + 1, sec.title, sec.bullets, section_images[i]))
    pages.append(_end_slide())

    # Render
    images = []
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page(viewport={"width": 1280, "height": 720})
        for html in pages:
            await page.set_content(html, wait_until="networkidle")
            images.append(await page.screenshot(type="png"))
        await browser.close()

    return images
