from __future__ import annotations

import io
from pathlib import Path
from typing import Union

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

from core.content_structurer import PresentationOutline


# Color scheme
BG_DARK = RGBColor(0x1A, 0x1A, 0x2E)
BG_SECTION = RGBColor(0x16, 0x21, 0x3E)
ACCENT = RGBColor(0x00, 0xD2, 0xFF)
TEXT_WHITE = RGBColor(0xFF, 0xFF, 0xFF)
TEXT_LIGHT = RGBColor(0xCC, 0xCC, 0xCC)
BULLET_COLOR = RGBColor(0x00, 0xD2, 0xFF)


def _set_slide_bg(slide, color: RGBColor):
    """Set solid background color for a slide."""
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_text_box(slide, left, top, width, height, text, font_size, color, bold=False, alignment=PP_ALIGN.LEFT):
    """Add a text box to a slide."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.alignment = alignment
    return txBox


def _create_title_slide(prs: Presentation, outline: PresentationOutline):
    """Create the title slide."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
    _set_slide_bg(slide, BG_DARK)

    # Accent line
    shape = slide.shapes.add_shape(
        1, Inches(1), Inches(2.5), Inches(2), Emu(40000)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = ACCENT
    shape.line.fill.background()

    # Title
    _add_text_box(
        slide, Inches(1), Inches(2.8), Inches(8), Inches(1.5),
        outline.title, 36, TEXT_WHITE, bold=True,
    )

    # Subtitle
    _add_text_box(
        slide, Inches(1), Inches(4.3), Inches(8), Inches(0.8),
        outline.subtitle, 18, TEXT_LIGHT,
    )


def _create_section_slide(prs: Presentation, section_num: int, title: str, bullets: list[str]):
    """Create a content slide for a section."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
    _set_slide_bg(slide, BG_SECTION)

    # Section number badge
    _add_text_box(
        slide, Inches(0.8), Inches(0.5), Inches(0.6), Inches(0.5),
        f"{section_num:02d}", 14, ACCENT, bold=True,
    )

    # Section title
    _add_text_box(
        slide, Inches(0.8), Inches(1.0), Inches(8.4), Inches(0.8),
        title, 28, TEXT_WHITE, bold=True,
    )

    # Accent line under title
    shape = slide.shapes.add_shape(
        1, Inches(0.8), Inches(1.75), Inches(1.5), Emu(30000)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = ACCENT
    shape.line.fill.background()

    # Bullets
    y = Inches(2.1)
    for bullet in bullets:
        # Bullet dot
        _add_text_box(
            slide, Inches(0.8), y, Inches(0.3), Inches(0.4),
            "●", 10, ACCENT,
        )
        # Bullet text
        _add_text_box(
            slide, Inches(1.2), y, Inches(8.0), Inches(0.5),
            bullet, 16, TEXT_LIGHT,
        )
        y += Inches(0.6)


def _create_end_slide(prs: Presentation):
    """Create the ending slide."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BG_DARK)

    _add_text_box(
        slide, Inches(0), Inches(3.0), Inches(10), Inches(1.0),
        "谢谢观看", 40, TEXT_WHITE, bold=True, alignment=PP_ALIGN.CENTER,
    )

    _add_text_box(
        slide, Inches(0), Inches(4.2), Inches(10), Inches(0.5),
        "Generated by Media Tool", 14, TEXT_LIGHT, alignment=PP_ALIGN.CENTER,
    )


def generate_ppt(outline: PresentationOutline) -> bytes:
    """Generate a PowerPoint presentation from an outline. Returns .pptx bytes."""
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(5.625)  # 16:9

    # Title slide
    _create_title_slide(prs, outline)

    # Section slides
    for i, section in enumerate(outline.sections, 1):
        _create_section_slide(prs, i, section.title, section.bullets)

    # End slide
    _create_end_slide(prs)

    # Save to bytes
    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def save_ppt(outline: PresentationOutline, output_path: Union[str, Path]) -> Path:
    """Generate and save PPT to a file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = generate_ppt(outline)
    path.write_bytes(data)
    return path
